// Derived navigation only. Source status, approval and meaning remain in the documents.
import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = await fs.realpath(fileURLToPath(new URL('../../../../', import.meta.url)));
const knowledge = path.join(root, 'docs/knowledge');
const index = path.join(knowledge, 'INDEX.md');
const excluded = new Set(['INDEX.md', 'README.md', 'governance.md']);
const digest = (bytes) => createHash('sha256').update(bytes).digest('hex');
const compare = (a, b) => a < b ? -1 : a > b ? 1 : 0;
const escape = (text) => text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/[\\[\]*_`|]/g, '\\$&');
const href = (relative) => relative.split('/').map((part) => encodeURIComponent(part).replace(/[!'()*]/g, (c) => '%' + c.charCodeAt(0).toString(16).toUpperCase())).join('/');

async function localDirectory(directory, create = false) {
  if (create) await fs.mkdir(directory).catch((error) => { if (error.code !== 'EEXIST') throw error; });
  const stat = await fs.lstat(directory);
  if (!stat.isDirectory() || stat.isSymbolicLink()) throw new Error('Expected a local directory: ' + path.relative(root, directory));
}

function documentTitle(text, file) {
  const lines = text.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n').split('\n');
  let first = 0, fence = null, comment = false;
  if (lines[0] === '---') {
    const end = lines.findIndex((line, i) => i > 0 && (line === '---' || line === '...'));
    if (end < 0) throw new Error('Unclosed frontmatter: ' + file);
    first = end + 1;
  }
  for (const line of lines.slice(first)) {
    if (comment) {
      if (line.includes('-->')) comment = false;
      continue;
    }
    const delimiter = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/);
    if (fence) {
      if (delimiter && delimiter[1][0] === fence[0] && delimiter[1].length >= fence.length && !delimiter[2].trim()) fence = null;
      continue;
    }
    // A Markdown HTML comment block hides its entire closing line too.
    // Inspect it outside fences: code examples may contain literal comment markers.
    if (/^ {0,3}<!--/.test(line)) {
      comment = !line.includes('-->');
      continue;
    }
    if (delimiter) { fence = delimiter[1]; continue; }
    const heading = line.match(/^ {0,3}#\s+(.+?)\s*$/);
    if (heading) {
      const title = heading[1].replace(/\s+#+$/, '').trim();
      if (title) return title;
    }
  }
  if (comment) throw new Error('Unclosed HTML comment before document title: ' + file);
  throw new Error('Missing # document title: ' + file);
}

async function sources() {
  await localDirectory(path.join(root, 'docs'));
  await localDirectory(knowledge);
  const entries = [];
  let bytes = 0;
  async function visit(relative = '') {
    for (const name of (await fs.readdir(path.join(knowledge, relative))).sort(compare)) {
      const file = relative ? relative + '/' + name : name;
      if (excluded.has(file)) continue;
      const absolute = path.join(knowledge, file), stat = await fs.lstat(absolute);
      if (stat.isSymbolicLink()) throw new Error('Linked knowledge source: ' + file);
      if (stat.isDirectory()) await visit(file);
      else if (stat.isFile() && file.endsWith('.md')) {
        bytes += stat.size;
        if (entries.length >= 1000 || bytes > 8 * 1024 * 1024) throw new Error('Knowledge exceeds the 1000 file / 8 MiB scan limit.');
        const content = await fs.readFile(absolute);
        entries.push({ file, hash: digest(content), title: documentTitle(content.toString('utf8'), file) });
      }
    }
  }
  await visit();
  entries.sort((a, b) => compare(a.file, b.file));
  return entries;
}

function render(entries) {
  const heading = '# A projekttudás indexe\n\n' +
    '<!-- Generated by record-decision/scripts/update-index.mjs. Edit the source documents, then run --write. -->\n\n' +
    'Az indexet a tudástárat módosító agent generálja a források címe és útvonala alapján.\n' +
    'A státuszt, verziót, jóváhagyást és alkalmazhatóságot mindig a teljes dokumentumban ellenőrizd.\n' +
    'Üres találatnál a tudásfájlokban is keress.\n\n' +
    '[Használat](README.md) · [Karbantartási szabályok](governance.md)\n\n';
  if (!entries.length) return heading + 'Még nincs saját projektdokumentum a tudástárban. A [sablonok](../templates/) nem aktív követelmények.\n';
  return heading + '| Dokumentum | Helye a tudástárban |\n| --- | --- |\n' + entries.map(({ file, title }) =>
    '| [' + escape(title) + '](' + href(file) + ') | ' + escape(path.posix.dirname(file) === '.' ? 'Gyökér' : path.posix.dirname(file)) + ' |').join('\n') + '\n';
}

async function readIndex() {
  try {
    const stat = await fs.lstat(index);
    if (!stat.isFile() || stat.isSymbolicLink()) throw new Error('INDEX.md must be a local file.');
    return await fs.readFile(index, 'utf8');
  } catch (error) { if (error.code === 'ENOENT') return null; throw error; }
}

async function main() {
  const mode = process.argv[2] ?? '--check';
  if (process.argv.length > 3 || !['--check', '--write'].includes(mode)) throw new Error('Usage: node .agents/skills/record-decision/scripts/update-index.mjs [--check|--write]');
  let release = async () => {}, temporary;
  try {
    if (mode === '--write') {
      const runtime = path.join(root, '.agent-runtime');
      await localDirectory(runtime, true);
      const lock = path.join(runtime, 'knowledge-index.lock');
      let owner;
      try { owner = await fs.open(lock, 'wx', 0o600); }
      catch (error) { if (error.code === 'EEXIST') throw new Error('Index writer lock exists. Coordinate with the other writer; retry after it finishes.'); throw error; }
      release = async () => { await owner.close(); await fs.unlink(lock); };
    }
    const before = await sources(), previous = await readIndex(), expected = render(before);
    if (JSON.stringify(before) !== JSON.stringify(await sources())) throw new Error('Knowledge changed during indexing; retry when the source edit is complete.');
    if (previous === expected) { console.log('INDEX.md is current (' + before.length + ' documents).'); return; }
    if (mode === '--check') throw new Error('INDEX.md is stale or missing. The knowledge-writing agent must run update-index.mjs --write.');
    temporary = index + '.' + randomUUID() + '.tmp';
    await fs.writeFile(temporary, expected, { flag: 'wx' });
    if (await readIndex() !== previous) throw new Error('INDEX.md changed during generation; retry after coordinating writers.');
    await fs.rename(temporary, index);
    console.log('Updated INDEX.md (' + before.length + ' documents).');
  } finally {
    try {
      if (temporary) await fs.unlink(temporary).catch((error) => { if (error.code !== 'ENOENT') throw error; });
    } finally { await release(); }
  }
}

await main().catch((error) => { console.error(error.message); process.exitCode = 1; });
